version: '3.3'

services:
  samba:
    tty: true
    container_name: smbd
    volumes:
      - /home/Arquivos/smb/:/shared
    ports:
      - "445:445"
    build:
      context: .
      dockerfile: Dockerfile