DECLARE OR REPLACE PROCEDURE SP_CONFERE_NM_FUNCIONARIO (P_ID_FUNCIONARIO NUMBER, P_NM_FUNCIONARIO VARCHAR2) IS 
  V_NM_FUNCIONARIO employees.first_name%TYPE;
  V_JOB_ID employees.JOB_ID%TYPE;
BEGIN
  SELECT first_name INTO V_NM_FUNCIONARIO
  FROM employees
  WHERE employee_id = P_ID_FUNCIONARIO;
  IF V_NM_FUNCIONARIO <> P_NM_FUNCIONARIO THEN 
    DBMS_OUTPUT.put_line(V_NM_FUNCIONARIO);
  ELSE 
    DBMS_OUTPUT.put_line('NOK');
  END IF;

END

SELECT * from employees

-- >, <, =, <>, !=, =<, =>